//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdaja_Service.Data
{
    using System;
    
    public partial class esp_GetRacunByIzlazID_Result1
    {
        public int IzlazID { get; set; }
        public System.DateTime Datum { get; set; }
        public string Naziv { get; set; }
        public decimal Cijena { get; set; }
        public int Kolicina { get; set; }
        public Nullable<decimal> Popust { get; set; }
        public string Sifra { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Broj_računa { get; set; }
        public decimal Iznos_bez_PDV_a { get; set; }
        public decimal Iznos_sa_PDV_om { get; set; }
        public string Jedinica_mjere { get; set; }
    }
}
